---
kind: pipeline
type: kubernetes
name: docker-image

image_pull_secrets:
  - drone_dockerconfig

steps:
- name: git-metadata
  image: prod-docker-parchment-docker-jfrog-io.us-west-2.aws.parchment.com/drone-plugins/git-metadata:stable
  pull: always
  settings:
- name: pre-commit-verify
  image: prod-docker-parchment-docker-jfrog-io.us-west-2.aws.parchment.com/drone-plugins/ruby-builder:stable
  depends_on: [git-metadata]
  pull: always
  commands:
    - /pre-commit-verify.rb
  when:
    event:
    - pull_request
- name: semver-get
  image: prod-docker-parchment-docker-jfrog-io.us-west-2.aws.parchment.com/drone-plugins/version-bump:stable
  depends_on: [git-metadata]
  pull: always
  settings:
    bump_only: 'true'
    semver_commit: 'false'
  when:
    event:
    - pull_request
- name: npmrc
  image: prod-docker-index-docker-io.us-west-2.aws.parchment.com/plugins/docker
  depends_on: [semver-get]
  commands:
    - touch /root/npm/.npmrc; chmod 600 /root/npm/.npmrc; echo "$NPMRC" > /root/npm/.npmrc
  volumes:
  - name: npm
    path: /root/npm
  when:
    event:
    - pull_request
- name: settings-xml
  image: prod-docker-index-docker-io.us-west-2.aws.parchment.com/infrastructureascode/aws-cli:1.16.220
  depends_on: [pre-commit-verify]
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
  volumes:
    - name: shared-m2
      path: /root/.m2
  commands:
    - aws s3 cp s3://parchment-chef/settings.xml /root/.m2/settings.xml
- name: build
  image: prod-docker-index-docker-io.us-west-2.aws.parchment.com/plugins/docker
  depends_on:
    - npmrc
    - settings-xml
  settings:
    daemon_off: 'true'
    repo: docker.pkg.github.com/parchment-io/dockerfiles-docker-git-builder/docker-git-builder
    registry: docker.pkg.github.com
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
      - latest
      - pr-${DRONE_PULL_REQUEST}
      - commit-${DRONE_COMMIT_SHA}
    build_args_from_env:
      - BUNDLE_PARCHMENT__JFROG__IO
      - NPM_CONFIG_USERCONFIG
      - MAVEN_USERNAME
      - MAVEN_PASSWORD
  privileged: true
  volumes:
  - name: dockersock
    path: /run
  - name: npm
    path: /root/npm
  - name: shared-gem
    path: /root/.gem
  - name: shared-npm
    path: /drone/src/.npm
  - name: shared-m2
    path: /root/.m2
  environment:
    BUNDLE_PARCHMENT__JFROG__IO:
      from_secret: bundler_ro
    NPM_CONFIG_USERCONFIG: /root/npm/.npmrc
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
    MAVEN_USERNAME:
      from_secret: maven_username
    MAVEN_PASSWORD:
      from_secret: maven_password
  when:
    event:
    - pull_request
- name: trivy-vuln-scan
  image: prod-docker-index-docker-io.us-west-2.aws.parchment.com/aquasec/trivy
  depends_on: [build]
  commands:
    - trivy --exit-code 1 --quiet --skip-dirs "/usr/lib/ruby/gems,/usr/local/bundle/" --severity CRITICAL docker.pkg.github.com/parchment-io/dockerfiles-docker-git-builder/docker-git-builder:pr-${DRONE_PULL_REQUEST}
  volumes:
  - name: dockersock
    path: /run
  when:
    event:
    - pull_request
- name: semver-commit
  image: prod-docker-parchment-docker-jfrog-io.us-west-2.aws.parchment.com/drone-plugins/version-bump:stable
  depends_on: [git-metadata]
  pull: always
  settings:
    bump_only: 'true'
  when:
    event:
    - push
    branch:
      include:
        - main
# See docker-retag plugin for more info on how to specify a new tag explicitly
- name: publish-version
  image: prod-docker-parchment-docker-jfrog-io.us-west-2.aws.parchment.com/drone-plugins/docker-retag:stable
  depends_on: [semver-commit]
  pull: always
  volumes:
  - name: dockersock
    path: /run
  settings:
    image: docker.pkg.github.com/parchment-io/dockerfiles-docker-git-builder/docker-git-builder
    create_git_tag: 'true'
    dockerconfig:
      from_secret: dockerconfig
  when:
    event:
    - push
    branch:
      include:
        - main

services:
- name: docker
  image: prod-docker-index-docker-io.us-west-2.aws.parchment.com/library/docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run
  settings:
    registry: docker.pkg.github.com
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

volumes:
- name: dockersock
  temp: {}
- name: npm
  temp: {}
- name: shared-gem
  host:
    path: /mnt/runner-shared/drone/.gem
- name: shared-npm
  host:
    path: /mnt/runner-shared/drone/.npm
- name: shared-m2
  host:
    path: /mnt/runner-shared/drone/.m2

trigger:
  event:
    - push
    - pull_request
  branch:
    - main
---
kind: pipeline
type: kubernetes
name: promote

image_pull_secrets:
  - drone_dockerconfig

steps:
- name: git-metadata
  image: prod-docker-parchment-docker-jfrog-io.us-west-2.aws.parchment.com/drone-plugins/git-metadata:stable
  pull: always
  settings:
- name: deployment-create
  image: prod-docker-parchment-docker-jfrog-io.us-west-2.aws.parchment.com/drone-plugins/github-deployment:stable
  pull: always
  settings:
    status: pending
    access_token:
      from_secret: github_token
- name: deployment-update
  image: prod-docker-parchment-docker-jfrog-io.us-west-2.aws.parchment.com/drone-plugins/github-deployment:stable
  pull: always
  settings:
    access_token:
      from_secret: github_token
  when:
    status:
    - success
    - failure

services:
- name: docker
  image: prod-docker-index-docker-io.us-west-2.aws.parchment.com/library/docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run

volumes:
- name: dockersock
  temp: {}

trigger:
  event:
    - promote
---
kind: secret
name: drone_dockerconfig
get:
  path: drone/data/ci
  name: dockerconfig
---
kind: secret
name: dockerconfig
get:
  path: drone/data/github
  name: dockerconfig
---
kind: secret
name: docker_username
get:
  path: drone/data/github
  name: docker_username
---
kind: secret
name: docker_password
get:
  path: drone/data/github
  name: docker_password
---
kind: secret
name: aws_access_key_id
get:
  path: drone/data/ci
  name: aws_access_key_id
---
kind: secret
name: aws_secret_access_key
get:
  path: drone/data/ci
  name: aws_secret_access_key
---
kind: secret
name: maven_username
get:
  path: drone/data/ci
  name: maven_username
---
kind: secret
name: maven_password
get:
  path: drone/data/ci
  name: maven_password
---
kind: secret
name: github_token
get:
  path: drone/data/github
  name: access_token
---
kind: secret
name: bundler_ro
get:
  path: drone/data/ci
  name: bundler_ro
---
kind: secret
name: npmrc
get:
  path: drone/data/ci
  name: npmrc
---
kind: signature
hmac: 4ded3ab5bfa196274aace9fce2f4087c7161ba03a1af04cb829069073ac20f31
